name: transparent_gif
description: A web app that uses AngularDart Components
# version: 1.0.0
homepage: https://github.com/dennougorilla/transparent_gif
author: dennougorilla <dennougorilla@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
  angular_components: 0.14.0-alpha+1  
  image: ^2.1.10
  gif_dart: 
    git: https://github.com/dennougorilla/gif_dart.git

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.0
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  test: ^1.6.0
